# -*- coding: utf-8 -*-
"""Fizzbuzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKtpcMt5CfZXVou25Aa_OZPWWzrXqYXh
"""

for program in range(1,101):
    if program % 3 == 0 and program % 5 == 0:
        print("FizzBuzz: "+str(program))
    elif program % 3 == 0:
        print("Fizz:" +str(program))
    elif program % 5 == 0:
        print("Buzz:" +str(program))
    else:
        print(program)